version: "3.8"

services:
  localstack:
    container_name: project-artemis-library-cloud-localstack
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: dynamodb,s3,sqs
