name: deploy
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.13
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARN_IAM_ROLE }}
          aws-region: ap-northeast-1
      - name: get bucket list
        run: aws s3 ls
      - name: head bucket
        run: aws s3api head-bucket --bucket $ARTIFACT_BUCKET
